### ISSUE TITLE
Build controllers for API

### ISSUE THREAD

**Issue by Ey-Jay** [Ey-Jay/backliner#1]
We need to test out models and build the controllers & routes for our API.

**Comment by jossdoe** [comment]
Required API Queries from the Frontend:
- get User data (Name, Avatar, Bands with Metadata through population)
- get Band data (Name, Avatar, Members with Metadata through population)
- get all Projects from Band (ID, Name, Theme, createdAt, updatedAt – virtual: amount of Lyrics, Audio, Video, Files included)
- get Project data (Name, Theme, createdAt, updatedAt, all Elements with metadata via virtuals)
- get all Lyrics (ID, title, author (populate), project_id, createdAt, updatedAt)
- get Lyrics ({...})
- get all Audios (ID, title, author (populate), project_id, createdAt, updatedAt)
- get Audio ({...})
- get all Videos (ID, title, author (populate), project_id, createdAt, updatedAt)
- get Video ({...})
- get all Files (ID, title, author (populate), project_id, createdAt, updatedAt)
- get File ({...})
- get Comments for Element with ID ({...})
